version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '04:00'
      timezone: 'Europe/Berlin'
    assignees:
      - 'ynnoig'
    reviewers:
      - 'ynnoig'
    commit-message:
      prefix: 'GA Dependabot: '
    labels:
      - 'github-actions'
      - 'dependencies'

  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '05:00'
      timezone: 'Europe/Berlin'
    assignees:
      - 'ynnoig'
    reviewers:
      - 'ynnoig'
    commit-message:
      prefix: 'Composer Dependabot: '
    labels:
      - 'composer'
      - 'dependencies'
